<?php

// Add each new, globally unique controller/service name here with its real file.
return [
    'BaseController' => 'core/BaseController.php',
    'RouteManager' => 'core/RouteManager.php',
    'DeveloperAccess' => 'core/DeveloperAccess.php',
    'Auth' => 'core/Auth.php',
    'CommerceAccess' => 'core/CommerceAccess.php',
    'StaffAudit' => 'core/StaffAudit.php',
    'CommerceValues' => 'core/CommerceValues.php',
    'CommerceDatabase' => 'core/CommerceDatabase.php',
    'Cache' => 'core/Cache.php',
    'CatalogReadService' => 'app/Services/CatalogReadService.php',
    'OrderStates' => 'core/OrderStates.php',
    'Queue' => 'core/Queue.php',
    'QueueService' => 'app/Services/QueueService.php',
    'JobRegistry' => 'app/Jobs/JobRegistry.php',
    'QueueWorker' => 'core/QueueWorker.php',
    'JobExecutionException' => 'core/QueueWorker.php',
    'NotificationJob' => 'app/Jobs/NotificationJob.php',
    'ProductService' => 'app/Services/ProductService.php',
    'InventoryService' => 'app/Services/InventoryService.php',
    'CartService' => 'app/Services/CartService.php',
    'AddressService' => 'app/Services/AddressService.php',
    'OrderService' => 'app/Services/OrderService.php',
    'RequestSecurity' => 'core/RequestSecurity.php',
    'RequestRejected' => 'core/RequestSecurity.php',
    'PrivateStorage' => 'core/PrivateStorage.php',
    'Mailer' => 'core/Mailer.php',
    'Welcome' => 'app/bridge/Welcome.php',
    'StorefrontProduct' => 'app/bridge/StorefrontProduct.php',
    'Cart' => 'app/bridge/Cart.php',
    'Admin' => 'app/bridge/Admin.php',
    ... (DEVELOPER_ENABLED ? ['Developer' => 'app/bridge/Developer.php'] : []),
];
