<?php
require __DIR__.'/support/CommerceTest.php';$pdo=CommerceTest::open();$check=[CommerceTest::class,'check'];$cache=new Cache();$reads=new CatalogReadService($pdo,$cache);$products=new ProductService($pdo);$inventory=new InventoryService($pdo);
$admin=CommerceAccess::provision('cache-admin@example.test','Disposable-Cache-Password');$user=CommerceTest::user('cache-customer@example.test');$cat=$products->saveCategory($admin,['slug'=>'cache-stones','name'=>'Cache Stones'],'category:cache:stones');
$input=['slug'=>'cache-marble','name'=>'Cache Marble','category_id'=>$cat,'status'=>'active','variants'=>[['sku'=>'CACHE-ONE','sell_unit'=>'sqft','qty_increment_milli'=>500,'unit_price_minor'=>12500]]];
$p=$products->save($admin,$input,0,'product:cache:create');$variant=$p['variant_ids'][0];
$first=$reads->detail('cache-marble');$same=$reads->detail('cache-marble');$check($first===$same&&$cache->stats['hit']===1,'Warm detail is a structured cache hit.');
$oldVersion=(int)$pdo->query("SELECT version FROM catalog_versions WHERE namespace='catalog'")->fetchColumn();
$parameters=['resource'=>'detail','slug'=>'cache-marble','contract'=>'public-v1','currency'=>'INR','locale'=>'en-IN'];$key=Cache::key($oldVersion,$parameters);$path=CommerceTest::$temp.'/private/cache/'.$key.'.json';
$check(is_file($path)&&(fileperms($path)&0777)===0600&&(fileperms(dirname($path))&0777)===0700,'File cache remains private with restrictive permissions.');
$input['id']=$p['id'];$input['variants'][0]['id']=$variant;$input['variants'][0]['unit_price_minor']=20000;$products->save($admin,$input,1,'product:cache:price');
$check((int)$reads->detail('cache-marble')['variants'][0]['unit_price_minor']===20000,'Committed price change immediately selects a new namespace.');
$inventory->adjust($admin,$variant,5000,'Warm stock','stock:cache:warm');$check($reads->detail('cache-marble')['in_stock'],'Committed stock change selects a new availability namespace.');
$cache->put($oldVersion,$parameters,$first);$current=$reads->detail('cache-marble');
$check((int)$current['variants'][0]['unit_price_minor']===20000&&$current['in_stock'],'Late old-version writer cannot poison a current read after commit.');
$check(is_file($path),'Correctness does not depend on deleting old external cache files.');
$version=(int)$pdo->query("SELECT version FROM catalog_versions WHERE namespace='catalog'")->fetchColumn();$currentPath=dirname($path).'/'.Cache::key($version,$parameters).'.json';
file_put_contents($currentPath,'broken json');$check((int)$reads->detail('cache-marble')['variants'][0]['unit_price_minor']===20000,'Corrupted JSON falls back to SQL.');
$record=json_decode(file_get_contents($currentPath),true);$record['expires_at']=1;file_put_contents($currentPath,json_encode($record));
$check($reads->detail('cache-marble')['in_stock'],'Expired entry falls back to authoritative data.');
$record=json_decode(file_get_contents($currentPath),true);$record['payload']=[];file_put_contents($currentPath,json_encode($record));
$check($reads->detail('cache-marble')['name']==='Cache Marble','Structurally invalid payload becomes a miss.');
$record=json_decode(file_get_contents($currentPath),true);$record['version']=$version-1;file_put_contents($currentPath,json_encode($record));
$check($reads->detail('cache-marble')['name']==='Cache Marble','Wrong envelope version becomes a miss.');
$record=json_decode(file_get_contents($currentPath),true);$record['payload']['csrf']='private';file_put_contents($currentPath,json_encode($record));
$check(!isset($reads->detail('cache-marble')['csrf']),'Private fields cannot survive a corrupted public cache entry.');
CommerceTest::fails(fn()=>Cache::key($version,['resource'=>'detail','user_id'=>$user]),'Identity cannot enter a public key.');
CommerceTest::fails(fn()=>$cache->put($version,$parameters,['email'=>'private@example.test']),'Private identity cannot enter a public payload.');
$normalizedA=CatalogReadService::filters(['page'=>'1','per_page'=>'12','q'=>' Marble ','user_id'=>$user,'csrf'=>'ignored']);$normalizedB=CatalogReadService::filters(['q'=>'Marble']);
$check($normalizedA===$normalizedB&&Cache::key($version,['resource'=>'listing',...$normalizedA])===Cache::key($version,['resource'=>'listing',...$normalizedB]),'Key normalization whitelists semantic public fields in fixed order.');
CommerceTest::rejects(fn()=>$reads->listing(['min_price_minor'=>5000,'max_price_minor'=>100]),422,'Inverted price range rejects before cache lookup.');
$reads->listing();$before=$cache->stats['hit'];$reads->listing();$check($cache->stats['hit']===$before+1,'Paginated catalog also warms and hits.');
$before=$cache->stats;$pdo->beginTransaction();$inside=$reads->detail('cache-marble');$pdo->rollBack();$check($inside['name']==='Cache Marble'&&$cache->stats===$before,'Transaction snapshot reads bypass cache and perform no file work under locks.');
$_ENV['CACHE_DRIVER']='none';$disabled=new Cache();$check((new CatalogReadService($pdo,$disabled))->detail('cache-marble')['name']==='Cache Marble'&&$disabled->stats['hit']===0,'Uncached mode preserves SQL behavior.');
$_ENV['CACHE_DRIVER']='redis';$_ENV['CACHE_REDIS_HOST']='127.0.0.1';$_ENV['CACHE_REDIS_PORT']='1';$fallback=new Cache();$redisReads=new CatalogReadService($pdo,$fallback);$check($redisReads->detail('cache-marble')['in_stock']&&$fallback->stats['failure']>=1,'Missing Redis client/connection falls back to private files and SQL.');
$_ENV['CACHE_DRIVER']='file';$original=$_ENV['PRIVATE_STORAGE_PATH'];$_ENV['PRIVATE_STORAGE_PATH']=dirname(__DIR__).'/assets/forbidden-cache';$bad=new Cache();
$check((new CatalogReadService($pdo,$bad))->detail('cache-marble')['in_stock']&&$bad->stats['failure']>=1&&!is_dir(dirname(__DIR__).'/assets/forbidden-cache'),'Unsafe/unavailable private cache path fails closed to SQL without creating public storage.');$_ENV['PRIVATE_STORAGE_PATH']=$original;
// Missing version metadata bypasses cache; no fabricated product result is returned.
$pdo->exec("DELETE FROM catalog_versions WHERE namespace='catalog'");$check($reads->detail('cache-marble')['name']==='Cache Marble','Missing durable version bypasses cache.');$pdo->prepare('INSERT INTO catalog_versions (namespace,version) VALUES (?,?)')->execute(['catalog',$version]);
$pdo->exec($pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?"CREATE TRIGGER cache_version_error BEFORE UPDATE ON catalog_versions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='injected'":"CREATE TRIGGER cache_version_error BEFORE UPDATE ON catalog_versions BEGIN SELECT RAISE(ABORT,'injected'); END");
CommerceTest::fails(fn()=>$inventory->adjust($admin,$variant,-1000,'Failed version','stock:cache:failure'),'Failed durable version advance prevents inventory commit.');$pdo->exec('DROP TRIGGER cache_version_error');
$check((int)$pdo->query("SELECT on_hand_milli FROM inventory WHERE variant_id=$variant")->fetchColumn()===5000,'Failed version rollback leaves authoritative stock unchanged.');
$cart=(new CartService($pdo))->change('user:'.$user,$variant,1000,0);$recorded=count(glob(dirname($path).'/*.json'));(new CartService($pdo))->get('user:'.$user);
$check(count(glob(dirname($path).'/*.json'))===$recorded,'Owned cart responses do not enter public file cache.');
$expired=dirname($path).'/'.str_repeat('a',64).'.json';file_put_contents($expired,json_encode(['expires_at'=>1]));$active=dirname($path).'/tmp-active';file_put_contents($active,'writer');
$check($cache->cleanup(100,2)>=1&&!is_file($expired)&&is_file($active),'Bounded cleanup removes expired entries while preserving temp writers.');
$check(glob(dirname($path).'/tmp-????????????????????????????????')===[],'Atomic publication leaves no completed temporary writes.');
CommerceTest::finish('Versioned private catalog cache');
