<?php
$escape = fn($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$url = fn($path) => $escape(base_url($path));
$isLogin = $page === 'login';
$definition = $isLogin ? ['Developer login', 'Protected operations workspace'] : DeveloperAccess::PAGES[$page];
$icons = ['overview'=>'◈','apis'=>'⇄','server'=>'▥','workflows'=>'◇','incidents'=>'△','activity'=>'≋','access'=>'⊙','settings'=>'⚙'];
$chart = function(string $kind, string $title) use ($escape): void { ?>
<div class="chart-wrap"><svg viewBox="0 0 640 180" preserveAspectRatio="none" role="img" aria-label="<?= $escape($title) ?>" class="chart" data-chart="<?= $escape($kind) ?>"><defs><linearGradient id="gradient-<?= $escape($kind) ?>" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#1c9b82" stop-opacity=".18"/><stop offset="1" stop-color="#1c9b82" stop-opacity="0"/></linearGradient></defs><path d="M0 20H640M0 65H640M0 110H640M0 155H640" stroke="#edf1f4" fill="none"/><path class="area" fill="url(#gradient-<?= $escape($kind) ?>)"/><path class="line" fill="none" stroke="#209d82" stroke-width="2.5"/><text class="empty-chart" x="320" y="90" text-anchor="middle" fill="#82919f" font-size="12">Waiting for observations</text></svg><div class="chart-axis"><span>Last 60 observations</span><span>Now</span></div></div>
<?php };
$flow = function(): void { ?>
<div class="flow-canvas"><div class="flow-title">CUSTOMER JOURNEY <span>Defined dependencies · execution not yet connected</span></div><div class="flow-lane"><div class="flow-node"><span class="node-icon">▦</span><strong>Catalog</strong><small>Product discovery</small><em>Planned</em></div><span class="connector">→</span><div class="flow-node"><span class="node-icon">▱</span><strong>Cart</strong><small>Items & quantities</small><em>Planned</em></div><span class="connector">→</span><div class="flow-node"><span class="node-icon">✓</span><strong>Checkout</strong><small>Stock & totals</small><em>Planned</em></div><span class="connector">→</span><div class="flow-node"><span class="node-icon">₹</span><strong>Payments</strong><small>Verified gateway event</small><em>Planned</em></div><span class="connector">→</span><div class="flow-node"><span class="node-icon">▣</span><strong>Orders</strong><small>Fulfilment & tracking</small><em>Planned</em></div></div><div class="flow-support"><span>Inventory <small>Reservation / release</small></span><span>Customers <small>Identity / addresses</small></span><span>Notifications <small>Order updates</small></span></div></div>
<?php };
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title><?= $escape($definition[0]) ?> · Maa Sarada Developer</title><link rel="stylesheet" href="<?= $url('assets/developer/console.css') ?>"></head>
<body class="<?= $isLogin ? 'login-page' : 'console-page' ?>">
<?php if ($isLogin): ?>
<main class="login-layout"><section class="login-story"><a class="brand light" href="<?= $url('') ?>"><span class="brand-mark">MS</span><span>Maa Sarada<small>DEVELOPER WORKSPACE</small></span></a><div class="story-content"><span class="overline">BUILT FOR YOUR COMMERCE SYSTEM</span><h1>Every request.<br>Every connection.<br>A clearer picture.</h1><p>Watch APIs, understand module flows, and keep your infrastructure in view from one protected workspace.</p><div class="story-diagram"><span>API</span><i></i><span>MODULE</span><i></i><span>EVENT</span></div></div><span class="story-footer">Marble & Sanitation · Operations console</span></section><section class="login-form-wrap"><div class="login-form"><span class="tag">RESTRICTED ACCESS</span><h2>Welcome back.</h2><p class="muted">Sign in to your developer workspace.</p><form method="post" action="<?= $url('developer/login') ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><label for="email">Email address</label><input type="email" name="email" id="email" placeholder="you@company.com" autocomplete="username" required autofocus maxlength="190"><label for="password">Password</label><div class="password-wrap"><input type="password" name="password" id="password" placeholder="Enter your password" autocomplete="current-password" required><button type="button" id="show-password" aria-label="Show password">Show</button></div><?php if ($error): ?><p class="login-error" role="alert"><?= $escape($error) ?></p><?php endif; ?><button class="button primary login-submit" type="submit">Sign in to console <span>→</span></button></form><p class="access-note">Access is checked against your role and permissions.<br>Contact your administrator if you need an account.</p><a class="back-link" href="<?= $url('') ?>">← Back to website</a></div><small class="login-foot">Protected session · No public registration</small></section></main>
<script>document.getElementById('show-password').onclick=function(){const input=document.getElementById('password');input.type=input.type==='password'?'text':'password';this.textContent=input.type==='password'?'Show':'Hide';this.setAttribute('aria-label',this.textContent+' password')};</script>
<?php else: ?>
<aside class="sidebar" id="sidebar"><a class="brand" href="<?= $url('developer') ?>"><span class="brand-mark">MS</span><span>Maa Sarada<small>DEVELOPER CONSOLE</small></span></a><div class="workspace"><span class="workspace-icon">◈</span><div>Commerce system<small>Operations workspace</small></div><span>⌄</span></div><div class="nav-label">MONITOR</div><nav aria-label="Developer pages"><?php foreach (DeveloperAccess::PAGES as $key => $item): if (!in_array($item[2], $account['permissions'], true)) continue; ?><a href="<?= $url($key === 'overview' ? 'developer' : 'developer/'.$key) ?>" class="nav-item <?= $page === $key ? 'active' : '' ?>" <?= $page === $key ? 'aria-current="page"' : '' ?>><span><?= $icons[$key] ?></span><?= $escape($item[0]) ?><?php if ($key === 'incidents'): ?><small>—</small><?php endif; ?></a><?php endforeach; ?></nav><div class="sidebar-foot"><span class="avatar"><?= $escape(strtoupper(substr($account['email'], 0, 1))) ?></span><div><?= $escape($account['role']) ?><small>Permission-protected access</small></div><form method="post" action="<?= $url('developer/logout') ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button aria-label="Sign out" title="Sign out">↪</button></form></div></aside>
<div class="app-shell"><header class="topbar"><div class="breadcrumb"><button id="menu-toggle" class="menu-toggle" aria-label="Toggle navigation" aria-expanded="false">☰</button><span>Developer</span><span>/</span><strong><?= $escape($definition[0]) ?></strong></div><div class="topbar-right"><span class="connection"><i id="connection-dot"></i><span id="connection">Connecting</span></span><span class="top-divider"></span><span class="avatar small"><?= $escape(strtoupper(substr($account['email'], 0, 1))) ?></span></div></header>
<main class="content" data-page="<?= $escape($page) ?>"><div class="page-heading"><div><span class="overline">COMMERCE OPERATIONS</span><h1><?= $escape($definition[0]) ?></h1><p><?= $escape($definition[1]) ?></p></div><div class="actions"><button class="button" id="pause" aria-pressed="false">Ⅱ Pause</button><button class="button primary" id="sample" aria-pressed="false">Preview sample data</button></div></div>
<?php if ($denied): ?><section class="panel empty-state"><span class="empty-icon">⊙</span><h2>Permission required</h2><p>Your role does not grant access to this page. Ask an administrator for <?= $escape($definition[2]) ?>.</p></section>
<?php else: ?>
<div class="data-notice" id="data-notice"><span>◉</span><div><strong>Runtime connected when available.</strong> API traffic, traces and incidents await collectors. Preview sample data to explore the design.</div><span class="notice-label">FOUNDATION</span></div>
<?php if ($page === 'overview'): ?>
<section class="stat-grid"><article class="stat-card"><span class="stat-icon">⇄</span><span class="stat-label">API requests</span><strong data-value="requests">—</strong><small>Total observed · collector required</small></article><article class="stat-card"><span class="stat-icon">↗</span><span class="stat-label">Requests / sec</span><strong data-value="rate">—</strong><small>Incoming request throughput</small></article><article class="stat-card"><span class="stat-icon amber">△</span><span class="stat-label">Failure rate</span><strong data-value="errors">—</strong><small>Classified API failures</small></article><article class="stat-card"><span class="stat-icon blue">▥</span><span class="stat-label">Registered APIs</span><strong data-value="registered">—</strong><small>Loaded application routes</small></article></section>
<div class="two-columns"><section class="panel"><div class="panel-head"><div><h2>Request throughput</h2><p>Observe traffic as it moves through your system</p></div><span class="legend"><i></i><span data-source>Awaiting collector</span></span></div><?php $chart('traffic', 'API request throughput'); ?></section><section class="panel"><div class="panel-head"><div><h2>Runtime snapshot</h2><p>Latest PHP process readings</p></div><a href="<?= $url('developer/server') ?>" class="text-link">Details ↗</a></div><div class="metric-row"><span>1 minute load average</span><strong data-value="load">—</strong></div><div class="metric-row"><span>PHP request memory</span><strong data-value="memory">—</strong></div><div class="metric-row"><span>CPU utilization</span><span class="status neutral">Collector required</span></div><p class="panel-note">Request memory is not total host memory.</p></section></div>
<section class="panel"><div class="panel-head"><div><h2>Commerce data flow</h2><p>Understand the connections between your modules</p></div><a href="<?= $url('developer/workflows') ?>" class="text-link">Explore flows ↗</a></div><?php $flow(); ?></section>
<div class="two-columns"><section class="panel"><div class="panel-head"><div><h2>Endpoint watch</h2><p>Registered APIs and planned commerce contracts</p></div><a href="<?= $url('developer/apis') ?>" class="text-link">All APIs ↗</a></div><div class="table-wrap"><table><thead><tr><th>Endpoint</th><th>Module</th><th>State</th></tr></thead><tbody id="overview-endpoints"><tr><td colspan="3" class="muted">Waiting for route registry</td></tr></tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p>Runtime observations and sample events</p></div><span class="status neutral">Read only</span></div><ul class="event-list" data-events><li class="muted">Waiting for observations.</li></ul></section></div>
<?php elseif ($page === 'apis'): ?>
<section class="stat-grid three"><article class="stat-card"><span class="stat-label">Registered endpoints</span><strong data-value="registered">—</strong><small>Discovered from route definitions</small></article><article class="stat-card"><span class="stat-label">Requests / second</span><strong data-value="rate">—</strong><small>Requires traffic instrumentation</small></article><article class="stat-card"><span class="stat-label">Average response</span><strong data-value="latency">—</strong><small>Requires duration collection</small></article></section><section class="panel"><div class="panel-head"><div><h2>Endpoint registry</h2><p>Search grows with your API collection</p></div><span class="status neutral" id="result-count">0 endpoints</span></div><div class="filter-bar"><label class="search-box"><span>⌕</span><input id="api-search" type="search" placeholder="Search endpoint, module or permission" aria-label="Search APIs"></label><select id="module-filter" aria-label="Filter by module"><option value="">All modules</option><option>Developer</option><option>Catalog</option><option>Cart</option><option>Checkout</option><option>Orders</option></select></div><div class="table-wrap"><table><thead><tr><th>Method / Endpoint</th><th>Module</th><th>Permission</th><th>State</th><th>Requests</th><th>Latency</th></tr></thead><tbody id="api-rows"></tbody></table></div><div class="table-footer"><span id="table-count">Waiting for registry</span><div><button class="button compact" id="previous">← Previous</button><span id="page-count">1 / 1</span><button class="button compact" id="next">Next →</button></div></div></section>
<?php elseif ($page === 'server'): ?>
<section class="stat-grid three"><article class="stat-card"><span class="stat-label">1 minute load average</span><strong data-value="load">—</strong><small>Available on supported operating systems</small></article><article class="stat-card"><span class="stat-label">PHP request memory</span><strong data-value="memory">—</strong><small>Metrics request · not total host usage</small></article><article class="stat-card"><span class="stat-label">Host CPU utilization</span><strong>—</strong><small>Independent host collector required</small></article></section><section class="panel"><div class="panel-head"><div><h2>Load history</h2><p>Continuous samples while this page is active</p></div><span class="legend"><i></i>1 minute average</span></div><?php $chart('load', 'Server load average history'); ?></section><div class="two-columns equal"><section class="panel"><div class="panel-head"><h2>Infrastructure collectors</h2></div><?php foreach (['Host memory','Disk usage','Active workers','Database connections','Queue depth','External availability'] as $metric): ?><div class="metric-row"><span><?= $metric ?></span><span class="status neutral">Not connected</span></div><?php endforeach; ?></section><section class="panel"><div class="panel-head"><h2>Collection policy</h2></div><div class="metric-row"><span>Refresh interval</span><strong>5 seconds</strong></div><div class="metric-row"><span>Hidden tab</span><strong>Polling paused</strong></div><div class="metric-row"><span>Request timeout</span><strong>4 seconds</strong></div><p class="panel-note">Load average is runnable/waiting work, not CPU percent. An external collector is required to detect server outages and collect host capacity.</p></section></div>
<?php elseif ($page === 'workflows'): ?>
<section class="panel"><div class="panel-head"><div><h2>Module dependency map</h2><p>Planned commerce architecture · live execution will use correlated traces</p></div><span class="status neutral">Health unknown</span></div><?php $flow(); ?><div class="flow-controls"><button class="button compact" id="zoom-out" aria-label="Zoom out">−</button><span id="zoom-label">100%</span><button class="button compact" id="zoom-in" aria-label="Zoom in">+</button><button class="button compact" id="zoom-reset">Reset</button><span class="muted">Select a module for details</span></div></section><div class="two-columns equal"><section class="panel" id="module-details"><div class="panel-head"><h2>Module details</h2><span class="status neutral">Definition</span></div><h3 id="module-name">Catalog</h3><p id="module-description" class="muted">Product discovery, categories, variants and availability.</p><div class="metric-row"><span>Implementation</span><strong>Planned</strong></div><div class="metric-row"><span>Observed executions</span><strong>Not connected</strong></div><div class="metric-row"><span>Health</span><strong>Unknown</strong></div></section><section class="panel"><div class="panel-head"><h2>Execution traces</h2><span class="status neutral">Collector required</span></div><div class="empty-state small-empty"><span class="empty-icon">◇</span><h3>No recorded traces yet</h3><p>Request IDs and parent events will reveal step duration, dependencies and the failure point.</p></div></section></div>
<?php elseif ($page === 'incidents'): ?>
<section class="stat-grid three"><article class="stat-card"><span class="stat-label">Open incidents</span><strong data-value="incidents">—</strong><small>Awaiting incident collector</small></article><article class="stat-card"><span class="stat-label">Acknowledged</span><strong data-value="acknowledged">—</strong><small>Under investigation</small></article><article class="stat-card"><span class="stat-label">Recovered</span><strong data-value="resolved">—</strong><small>Verified or manually resolved</small></article></section><section class="panel"><div class="panel-head"><div><h2>Incident inbox</h2><p>Grouped failures with severity, ownership and recovery</p></div><select id="incident-filter" aria-label="Incident status"><option value="">All states</option><option>Open</option><option>Acknowledged</option><option>Resolved</option></select></div><div id="incident-list" class="empty-state"><span class="empty-icon">△</span><h3>Incident collection is not connected</h3><p>This does not indicate a healthy system. Enable sample preview to inspect the incident layout.</p></div></section>
<?php elseif ($page === 'activity'): ?>
<section class="panel"><div class="panel-head"><div><h2>Live event stream</h2><p>New observations appear without a page reload</p></div><button class="button compact" id="clear-events">Clear visible events</button></div><div class="stream-caption"><span class="status neutral">Bounded to 30 recent observations</span><span class="muted">Runtime sampling is separate from API request capture</span></div><ul class="event-list large-events" data-events><li class="muted">Waiting for observations.</li></ul></section>
<?php elseif ($page === 'access'): ?>
<section class="panel"><div class="panel-head"><div><h2>Your access policy</h2><p>Permissions are rechecked against your account on each request</p></div><span class="status green"><?= $escape($account['role']) ?></span></div><div class="metric-row"><span>Signed-in account</span><strong><?= $escape($account['email']) ?></strong></div><div class="metric-row"><span>Console access</span><strong>developer.view</strong></div><div class="metric-row"><span>Inactivity timeout</span><strong>30 minutes</strong></div><div class="table-wrap"><table><thead><tr><th>Page</th><th>Required permission</th><th>Your access</th></tr></thead><tbody><?php foreach (DeveloperAccess::PAGES as $item): ?><tr><td><?= $escape($item[0]) ?></td><td><code><?= $escape($item[2]) ?></code></td><td><span class="status <?= in_array($item[2],$account['permissions'],true) ? 'green':'neutral' ?>"><?= in_array($item[2],$account['permissions'],true) ? 'Granted':'Not granted' ?></span></td></tr><?php endforeach; ?></tbody></table></div><p class="panel-note">Role editing, user assignments and audit history are planned. This page is read-only; it does not grant or modify permissions.</p></section>
<?php elseif ($page === 'settings'): ?>
<div class="two-columns equal"><section class="panel"><div class="panel-head"><div><h2>Console configuration</h2><p>Current effective settings · read only</p></div></div><div class="metric-row"><span>Developer console</span><span class="status green">Enabled</span></div><div class="metric-row"><span>Configuration flag</span><code>DEVELOPER_ENABLED</code></div><div class="metric-row"><span>Refresh interval</span><strong>5 seconds</strong></div><div class="metric-row"><span>Transport</span><strong>Polling</strong></div><div class="metric-row"><span>Diagnostics payloads</span><strong>Not collected</strong></div><p class="panel-note">Set DEVELOPER_ENABLED=false in .env to remove the console pages and metrics API.</p></section><section class="panel"><div class="panel-head"><h2>Monitoring roadmap</h2></div><div class="roadmap-item"><span>01</span><div><strong>API instrumentation</strong><p>Incoming/outgoing timing, classification and safe event storage.</p></div></div><div class="roadmap-item"><span>02</span><div><strong>Infrastructure collectors</strong><p>CPU, host memory, workers, database health and availability.</p></div></div><div class="roadmap-item"><span>03</span><div><strong>Traces & incident rules</strong><p>Module execution, grouping, retention and severity thresholds.</p></div></div><div class="roadmap-item"><span>04</span><div><strong>Alerts & streaming</strong><p>Queued notifications, cooldowns and an optional SSE transport.</p></div></div></section></div>
<?php endif; ?>
<?php endif; ?>
<footer class="content-footer"><span><i class="footer-dot"></i> Role & permission based access <span>·</span> Read-only monitoring foundation</span><span id="updated" role="status">Waiting for first observation</span></footer></main></div>
<div id="detail-dialog" class="detail-dialog" hidden role="dialog" aria-modal="true" aria-labelledby="detail-title"><div class="detail-inner"><button id="close-detail" class="button compact">Close ×</button><span class="overline">ENDPOINT DETAILS</span><h2 id="detail-title"></h2><pre id="detail-body"></pre></div></div>
<script>window.consoleConfig=<?= json_encode(['endpoint'=>base_url('index.php?route=api/developer/metrics'), 'login'=>base_url('developer/login'), 'denied'=>$denied, 'permissions'=>$account['permissions']],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;</script><script src="<?= $url('assets/developer/console.js') ?>" defer></script>
<?php endif; ?></body></html>
