'use strict';
const paths={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',heart:'<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>',bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',truck:'<path d="M2 5h12v12H2zM14 10h4l4 4v3h-8"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>',spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z"/>',return:'<path d="M4 9a8 8 0 1 1 0 7M4 3v6h6"/>',headphones:'<path d="M3 15v-3a9 9 0 0 1 18 0v3M3 13h4v8H3zM17 13h4v8h-4z"/>',award:'<circle cx="12" cy="9" r="7"/><path d="m8 15-2 7 6-3 6 3-2-7m-7-6 2 2 4-4"/>',slab:'<path d="M5 3h14v18H5zM5 12l8-9M10 21l9-10M5 17l6-7"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',basin:'<path d="M2 11h20c0 7-4 9-10 9S2 18 2 11Zm10 0V5a3 3 0 0 1 6 0M8 22h8"/>',tap:'<path d="M10 21V7a4 4 0 0 1 4-4h5v4h-5v14M6 21h12M9 11H4V8h6"/>',shower:'<path d="M18 22V5a3 3 0 0 0-6 0v2M6 10h12L12 7l-6 3ZM7 14v1m5-1v1m5-1v1M7 19v1m5-1v1m5-1v1"/>',toilet:'<path d="M6 3h11v9H6zM3 12h18c0 5-5 6-5 6l1 4H8l1-4s-6-1-6-6Z"/>',tools:'<path d="m4 20 12-12M14 3a5 5 0 0 0 7 7l-5-1-1-5M3 17l4 4M3 3l5 5m-2-5 15 15-3 3L3 6Z"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.slab}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));
const categories=[['Marble','120+ selections','slab'],['Granite','85+ selections','slab'],['Tiles','200+ selections','grid'],['Wash basins','60+ selections','basin'],['Faucets','95+ selections','tap'],['Showers','45+ selections','shower'],['Sanitaryware','70+ selections','toilet'],['Accessories','110+ selections','tools']];
document.querySelector('.categories').innerHTML=categories.map(([name,count,ic])=>`<a href="${['Wash basins','Faucets','Showers','Sanitaryware'].includes(name)?'#arrivals':'#deals'}" class="category"><span class="category-icon">${icon(ic)}</span>${name}<small>${count}</small></a>`).join('')+`<a href="#collections" class="category view-all"><span class="category-icon">${icon('grid')}</span>View all<br>categories</a>`;
const products=[{id:1,name:'Statuario Italian Marble',type:'Premium natural stone',art:'slab marble',price:450,old:600,unit:'/ sq. ft.',discount:25,rating:128},{id:2,name:'Black Galaxy Granite',type:'Polished · 18 mm',art:'slab dark-stone',price:180,old:240,unit:'/ sq. ft.',discount:25,rating:96},{id:3,name:'Designer Table Top Basin',type:'Ceramic · Alpine white',art:'basin',price:3499,old:4999,discount:30,rating:84},{id:4,name:'Brushed Gold Basin Mixer',type:'Single lever · Brass',art:'tap gold',price:4299,old:5999,discount:28,rating:112},{id:5,name:'Botticino Classic Marble',type:'Natural beige · Polished',art:'slab cream-stone',price:220,old:290,unit:'/ sq. ft.',discount:24,rating:73},{id:6,name:'Rainfall Shower System',type:'Chrome · Overhead shower',art:'shower',price:6499,old:8999,discount:28,rating:65},{id:7,name:'Nero Designer Wash Basin',type:'Matte black · Ceramic',art:'basin round black',price:4999,old:6500,rating:32},{id:8,name:'Calacatta Gold Marble',type:'Signature Italian collection',art:'slab marble',price:650,old:800,unit:'/ sq. ft.',rating:48},{id:9,name:'Arc Chrome Basin Mixer',type:'Modern brassware collection',art:'tap',price:3299,old:4200,rating:27},{id:10,name:'Terrazzo Stone Tile',type:'Natural texture · 600 × 600',art:'slab terrazzo',price:125,old:160,unit:'/ sq. ft.',rating:39}];
const money=n=>'₹'+n.toLocaleString('en-IN');
let cart={},saved=[];try{cart=JSON.parse(localStorage.getItem('maa-cart')||'{}');saved=JSON.parse(localStorage.getItem('maa-saved')||'[]');if(!cart||typeof cart!=='object'||Array.isArray(cart))cart={};if(!Array.isArray(saved))saved=[];}catch{cart={};saved=[];}
function card(p,isNew=false){return `<article class="product" data-product="${p.id}"><span class="discount ${isNew?'new':''}">${isNew?'NEW':`−${p.discount}%`}</span><button class="wish ${saved.includes(p.id)?'selected':''}" data-wish="${p.id}" aria-label="Save ${p.name}" aria-pressed="${saved.includes(p.id)}">${icon('heart')}</button><div class="product-image" role="img" aria-label="Illustrative ${p.name}"><div class="${p.art}"></div></div><h3>${p.name}</h3><span class="type">${p.type}</span><div class="price"><del>${money(p.old)}</del><strong>${money(p.price)} <small>${p.unit||''}</small></strong></div><div class="product-bottom"><span class="stars" aria-label="Rated 4.8 out of 5">★★★★★ <small>(${p.rating})</small></span><button class="add-cart" data-add="${p.id}" aria-label="Add ${p.name} to bag">${icon('bag')}</button></div></article>`;}
document.querySelector('#deals-grid').innerHTML=products.slice(0,6).map(p=>card(p)).join('');document.querySelector('#arrivals-grid').innerHTML=products.slice(6).map(p=>card(p,true)).join('');
document.querySelector('#best-grid').innerHTML=[products[0],products[2],products[1],products[3],products[5]].map((p,i)=>`<article class="best"><div><span class="best-number">0${i+1}</span><h3>${p.name}</h3><div class="price"><strong>${money(p.price)}</strong><del>${money(p.old)}</del></div><div class="stars">★★★★★</div></div><div class="product-image"><div class="${p.art}"></div></div><button class="add-cart" data-add="${p.id}" aria-label="Add ${p.name} to bag">${icon('bag')}</button></article>`).join('');
let toastTimer;function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),5000);}
function persist(){try{localStorage.setItem('maa-cart',JSON.stringify(cart));localStorage.setItem('maa-saved',JSON.stringify(saved));}catch{}updateCounts();}
function updateCounts(){document.querySelector('#cart-count').textContent=Object.entries(cart).reduce((n,[id,q])=>n+(products.some(p=>p.id===Number(id))&&Number.isInteger(q)&&q>0?q:0),0);const w=document.querySelector('#wish-count');w.textContent=saved.length;w.hidden=!saved.length;}updateCounts();
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const id=Number(add.dataset.add);cart[id]=(Number.isInteger(cart[id])?cart[id]:0)+1;persist();toast('Added to your shopping bag');}const wish=e.target.closest('[data-wish]');if(wish){const id=Number(wish.dataset.wish);saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];wish.classList.toggle('selected',saved.includes(id));wish.setAttribute('aria-pressed',String(saved.includes(id)));persist();toast(saved.includes(id)?'Saved to your favourites':'Removed from your favourites');}const info=e.target.closest('[data-info]');if(info)toast(info.dataset.info);const remove=e.target.closest('[data-remove]');if(remove){delete cart[remove.dataset.remove];persist();renderCart();}});
function renderCart(){let total=0;const rows=Object.entries(cart).filter(([id,q])=>products.some(p=>p.id===Number(id))&&Number.isInteger(q)&&q>0).map(([id,qty])=>{const p=products.find(p=>p.id===Number(id));total+=p.price*qty;return `<div class="cart-row"><div><b>${p.name}</b><small>${qty} ${p.unit?'sq. ft.':'item(s)'} × ${money(p.price)}</small></div><strong>${money(p.price*qty)}</strong><button data-remove="${p.id}">Remove</button></div>`;});document.querySelector('#cart-items').innerHTML=rows.join('')||'<p>Your bag is waiting for something beautiful.</p>';document.querySelector('#cart-total').textContent=rows.length?`Estimated subtotal: ${money(total)}`:'';}
const dialog=document.querySelector('#cart-dialog');document.querySelector('#cart-toggle').onclick=()=>{renderCart();dialog.showModal();};document.querySelector('#close-cart').onclick=()=>dialog.close();document.querySelector('#continue-shopping').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
let savedOnly=false;function filterProducts(query=''){document.querySelectorAll('.product').forEach(el=>{const p=products.find(p=>p.id===Number(el.dataset.product));el.hidden=!(p.name+' '+p.type).toLowerCase().includes(query.toLowerCase())||(savedOnly&&!saved.includes(p.id));});document.querySelector('#search-empty').hidden=[...document.querySelectorAll('#deals-grid .product')].some(el=>!el.hidden);}
document.querySelector('.search').addEventListener('submit',e=>{e.preventDefault();savedOnly=false;filterProducts(e.target.querySelector('input').value.trim());document.querySelector('#deals').scrollIntoView({behavior:'smooth'});});document.querySelector('.search input').addEventListener('input',e=>{if(!e.target.value)filterProducts();});document.querySelector('#wishlist-toggle').onclick=()=>{savedOnly=!savedOnly;filterProducts();document.querySelector('#deals').scrollIntoView({behavior:'smooth'});toast(savedOnly?'Showing your saved products':'Showing all products');};document.querySelector('#all-deals').onclick=()=>{savedOnly=false;document.querySelector('.search input').value='';filterProducts();};
const toggle=document.querySelector('.mobile-toggle');toggle.onclick=()=>{const open=document.querySelector('nav').classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));};document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('nav').classList.remove('open');toggle.setAttribute('aria-expanded','false');}));
const slides=[{image:'interior.jpg',alt:'Elegant living room with natural materials',eyebrow:"NATURE’S ART. YOUR HOME.",title:'Timeless stone.<br>Extraordinary<br><em>spaces.</em>',description:'Exquisite marble & thoughtful bath essentials.<br>Crafted by nature. Curated for you.',caption:'THE SIGNATURE COLLECTION'},{image:'bathroom.jpg',alt:'Luxurious bathroom with stone surfaces',eyebrow:'YOUR PERSONAL SANCTUARY',title:'Quiet luxury.<br>Everyday<br><em>rituals.</em>',description:'Beautiful basins and considered details.<br>Turn your bathroom into a retreat.',caption:'THE BATHROOM COLLECTION'},{image:'kitchen.jpg',alt:'Kitchen featuring natural stone countertops',eyebrow:'MADE FOR BEAUTIFUL LIVING',title:'Natural beauty.<br>Exceptional<br><em>living.</em>',description:'Surfaces with character. Quality that lasts.<br>Find the perfect finish for your home.',caption:'THE NATURAL STONE COLLECTION'}];let slideIndex=0;function showSlide(n){slideIndex=(n+slides.length)%slides.length;const s=slides[slideIndex];const img=document.querySelector('.hero-image');img.src='assets/'+s.image;img.alt=s.alt;document.querySelector('.hero-content .eyebrow').textContent=s.eyebrow;document.querySelector('.hero h1').innerHTML=s.title;document.querySelector('.hero p').innerHTML=s.description;document.querySelector('.hero-caption').innerHTML=`${s.caption}<span>0${slideIndex+1} / 03</span>`;document.querySelectorAll('.dots button').forEach((b,i)=>{b.classList.toggle('active',i===slideIndex);b.setAttribute('aria-pressed',String(i===slideIndex));});}document.querySelector('#next-slide').onclick=()=>showSlide(slideIndex+1);document.querySelector('#prev-slide').onclick=()=>showSlide(slideIndex-1);document.querySelectorAll('.dots button').forEach((b,i)=>b.onclick=()=>showSlide(i));
const end=Date.now()+(7*3600+45*60+32)*1000;function tick(){const seconds=Math.max(0,Math.floor((end-Date.now())/1000));document.querySelector('#hours').textContent=String(Math.floor(seconds/3600)).padStart(2,'0');document.querySelector('#minutes').textContent=String(Math.floor(seconds/60)%60).padStart(2,'0');document.querySelector('#seconds').textContent=String(seconds%60).padStart(2,'0');}tick();setInterval(tick,1000);
document.querySelector('#newsletter').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#newsletter-status').textContent='Thank you for your interest! Newsletter signup will open when our store launches.';});document.querySelector('#year').textContent=new Date().getFullYear();
